databases:
  - name: vikosen_DB
    databaseName: vikosen_db
    user: vikosen
    region: singapore

services:
  - type: web
    name: vikosen
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vikosen_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false